from fastapi import APIRouter, UploadFile, File, HTTPException
from app.models.schemas import ProcessResponse

router = APIRouter()


@router.post("/process-file", response_model=ProcessResponse)
async def process_file(file: UploadFile = File(...)):
    """
    POST /process-file
    Accepts an image file, runs OCR, cleans text, and returns AI-generated study content.

    NOTE: OCR, text cleaning, and AI service integrations will be added in Steps 2-7.
          This is a placeholder stub to verify routing works correctly.
    """
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Only image files are supported.")

    # Stubs — will be replaced step by step
    return ProcessResponse(
        explanation="[Stub] Explanation will be generated by AI in Step 7.",
        summary="[Stub] Summary will be generated by AI in Step 7.",
        key_points=["[Stub] Key points will be extracted in Step 7."],
        questions=["[Stub] Questions will be generated in Step 7."],
    )
